export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: `/user/auth/login`,
    SIGNUP: `/user/auth/signup`,
    LOGOUT: `/user/auth/logout`,
    OTP_REGISTER: `/user/auth/otp/register`,
    OTP_VERIFY: `/user/auth/otp/verify`,
    OTP_RESEND: `/user/auth/otp/resend`,
  },
  USER: {
    PROFILE: `/user/service`,
    PROFILE_BY_ID: `/user/service/:userId`,
    PROFILE_PICTURE: `/user/service/:userId/profile/picture`,
    PROFILE_BANNER: `/user/service/:userId/profile/banner`,
    PROFILE_DETAILS: `/user/service/:userId/profile/details`,
    FOLLOW: `/user/service/:userId/follow/:targetUserId`,
    UNFOLLOW: `/user/service/:userId/unfollow/:targetUserId`,
    FOLLOWERS: `/user/service/:userId/followers`,
    FOLLOWING: `/user/service/:userId/following`,
  },
  TOURNAMENT: {
    FETCH_ALL: `/tournament`,
    FETCH: `/tournament/:tournamentId`,
    CREATE: `/tournament`,
    UPDATE: `/tournament/:tournamentId`,
    DELETE: `/tournament/:tournamentId`,
    JOIN: `/tournament/:tournamentId/register`,
    LEAVE: `/tournament/:tournamentId/unregister`,
    GET_PARTICIPANTS: `/tournament/:tournamentId/participants`,
    FETCH_PARTICIPATED: `/tournament/participated/:userId`,
  },
  NOTIFICATION: {
    FETCH: `/user/service/:userId/notifications`,
    MARK_AS_READ: `/user/service/:userId/notifications/:notificationId/read`,
  },
  WEBRTC: {
    PUT_OFFER: `/webrtc/offer`,
    PUT_ANSWER: `/webrtc/answer`,
    GET_OFFER: `/webrtc/offer/:tournamentId/:userId`,
    GET_ANSWER: `/webrtc/answer/:tournamentId/:userId`,
  },
} as const;

export const ERROR_MESSAGES = {
  AUTH: {
    LOGIN: 'Login failed',
    SIGNUP: 'Signup failed',
    LOGOUT: 'Logout failed',
    OTP_REGISTER: 'OTP register failed',
    OTP_VERIFY: 'OTP verify failed',
    OTP_RESEND: 'OTP resend failed',
    DEFAULT: 'Something went wrong',
  },
  USER: {
    PROFILE: 'Profile fetch failed',
    PROFILE_BY_ID: 'Profile by id fetch failed',
    PROFILE_PICTURE: 'Profile picture fetch failed',
    PROFILE_BANNER: 'Profile banner fetch failed',
    PROFILE_DETAILS: 'Profile details fetch failed',
    FOLLOW: 'Follow failed',
    UNFOLLOW: 'Unfollow failed',
    FOLLOWERS: 'Followers fetch failed',
    FOLLOWING: 'Following fetch failed',
    NOTIFICATIONS: 'Notifications fetch failed',
    MARK_AS_READ: 'Mark as read failed',
  },
  TOURNAMENT: {
    CREATE: 'Tournament create failed',
    JOIN: 'Tournament join failed',
    LEAVE: 'Tournament leave failed',
    FETCH_ALL: 'Tournament fetch all failed',
    FETCH: 'Tournament fetch failed',
    DEFAULT: 'Something went wrong',
    DELETE: 'Tournament delete failed',
    UPDATE: 'Tournament update failed',
    GET_PARTICIPANTS: 'Tournament participants fetch failed',
    FETCH_PARTICIPATED: 'Tournament participated fetch failed',
  },
  WEBRTC: {
    PUT_OFFER: 'WebRTC offer put failed',
    PUT_ANSWER: 'WebRTC answer put failed',
    GET_OFFER: 'WebRTC offer get failed',
    GET_ANSWER: 'WebRTC answer get failed',
  },
} as const;

export const STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  SERVER_ERROR: 500,
} as const;
